[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "myeonggipop"
version = "2.1.0"
description = "Universal Korean OCR popup dictionary"
readme = "README.md"
license = "GPL-3.0"
authors = [
    {name = "rtr46"}
]
requires-python = ">=3.10"
dependencies = [
    "PyQt6>=6.9.1",
    "pynput>=1.7.8",
    "mss>=10.0.0",
    "requests>=2.32.4",
    "Pillow>=11.2.1",
    "betterproto>=2.0.0b7",
    "protobuf>=6.33.1",
    "websockets>=15.0.1",
    "keyboard~=0.13.5; sys_platform == 'win32'",
    "python-xlib~=0.33; sys_platform == 'linux'",
    "pyobjc-framework-Quartz>=10.0; sys_platform == 'darwin'",
    "pyobjc-framework-Cocoa>=10.0; sys_platform == 'darwin'",
    "platformdirs",
]

[project.scripts]
myeonggipop = "myeonggipop.main:main"

[project.entry-points."myeonggipop.scripts"]
build-dict = "myeonggipop.scripts.build_dictionary:main"
build-korean-deconjugator = "myeonggipop.scripts.build_korean_deconjugator:main"
import-yomitan-dict-html = "myeonggipop.scripts.import_yomitan_dict_html:main"
import-yomitan-dict-text = "myeonggipop.scripts.import_yomitan_dict_text:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["myeonggipop*"]

[tool.setuptools.package-data]
myeonggipop = ["scripts/deconjugator_ko.json", "resources/icon.ico", "resources/icon.inactive.ico"]