# .github/workflows/pr-build.yml
name: pre-release builds

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
  build-linux:
    uses: ./.github/workflows/build-linux.yml
  build-flatpak:
    uses: ./.github/workflows/build-flatpak.yml
  build-macos:
    uses: ./.github/workflows/build-macos.yml
